version: '2'
services:
    jhipsterreactapp-app:
        image: jhipsterreactapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterreactapp-postgresql:5432/jhipsterReactApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterreactapp-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterreactapp-postgresql
